#!/usr/bin/env bun
// Build entry: compiles the anonboard post program and regenerates mod.ts (the
// program id + instruction builders that node/batcher/frontend import).
import path from "node:path";
import fs from "node:fs";
import { spawnSync } from "node:child_process";
import {
  PublicKey,
  TransactionInstruction,
  SystemProgram,
} from "@solana/web3.js";
import { POST_PROGRAM_ID } from "../program-id.ts";

const PKG_DIR = import.meta.dirname!;
const ROOT = path.resolve(PKG_DIR, "..");
const PROGRAM_SO = path.join(ROOT, "build", "anonboard.so");

function buildProgramIfMissing() {
  // SKIP_SOLANA_BUILD=1 means "reuse the existing .so", not "never build".
  // It defaults to 1 in start.dev.ts / start.test.ts so repeat runs are fast,
  // but build/ is gitignored and nothing ships a pre-compiled anonboard.so — so
  // honouring the skip unconditionally made `bun run dev` and `bun run test`
  // fail on every fresh clone: compilation skipped, then "build/anonboard.so is
  // missing after build".
  if (process.env.SKIP_SOLANA_BUILD === "1") {
    if (fs.existsSync(PROGRAM_SO)) {
      console.log(
        `[contracts-solana] SKIP_SOLANA_BUILD=1 — reusing ${path.relative(ROOT, PROGRAM_SO)}`,
      );
      return;
    }
    console.log(
      "[contracts-solana] SKIP_SOLANA_BUILD=1 but build/anonboard.so is absent — compiling anyway",
    );
  }
  const result = spawnSync(
    process.execPath,
    [path.join(PKG_DIR, "build-program.ts")],
    { stdio: "inherit" },
  );
  if (result.status !== 0) {
    process.exit(typeof result.status === "number" ? result.status : 1);
  }
}

function writeMod() {
  const mod = `/* AUTO-GENERATED by scripts/build.ts — do not edit. */
export {
  POST_PROGRAM_ID,
  DISCRIMINANT_POST,
  DISCRIMINANT_CLOSE,
  POST_SEED,
  COUNTER_SEED,
  TAG_POST,
  TAG_COUNTER,
  MAX_BODY,
  POST_LAYOUT,
} from "./program-id.ts";
export {
  createPostInstruction,
  createCloseInstruction,
  counterPda,
  postPda,
  nextPostIndex,
} from "./instructions.ts";
export {
  decodePostAccount,
  type PostAccount,
} from "./post-account.ts";
export {
  DEV_RPC_URL,
  DEV_BATCHER_URL,
  DEV_NODE_API_URL,
  DEV_OPERATOR_URL,
  DEV_NAMESPACE,
  DEV_BATCHER_FEE_PAYER,
  DEV_BATCHER_TARGET,
} from "./dev-config.ts";
`;
  fs.writeFileSync(path.join(ROOT, "mod.ts"), mod);
}

buildProgramIfMissing();
writeMod();

if (!fs.existsSync(PROGRAM_SO)) {
  console.error(
    `[contracts-solana] build/anonboard.so is missing after build. Did cargo-build-sbf succeed?`,
  );
  process.exit(1);
}

console.log(
  `[contracts-solana] program id: ${POST_PROGRAM_ID}`,
);
console.log(
  `[contracts-solana] program .so: ${path.relative(ROOT, PROGRAM_SO)} (${
    fs.statSync(PROGRAM_SO).size
  } bytes)`,
);
