/* AUTO-GENERATED by scripts/build.ts — do not edit. */
export {
  COUNTER_PROGRAM_ID,
  DISCRIMINANT_INCREMENT,
  DISCRIMINANT_RESET,
  COUNTER_SEED,
} from "./program-id.ts";
export {
  findCounterAddress,
  createIncrementInstruction,
  createResetInstruction,
} from "./instructions.ts";
export {
  DEV_RPC_URL,
  DEV_BATCHER_URL,
  DEV_NODE_API_URL,
  DEV_NAMESPACE,
  DEV_BATCHER_FEE_PAYER,
  DEV_BATCHER_TARGET,
} from "./dev-config.ts";
